### ISSUE TITLE
Docker Compose up error

### ISSUE THREAD

**Issue by mwaseem75** [danoleg/mongo-to-iris-migration#15]
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Creating mongo-to-iris-migration_mongodb_1 ... 
Creating mongo-to-iris-migration_iris_1    ... 
Creating mongo-to-iris-migration_iris_1    ... error

Creating mongo-to-iris-migration_mongodb_1 ... done8f74c68049809b3edbf0c8bd1aea493668ef5c5ca8d5051300bef7): Bind for 0.0.0.0:52773 failed: port is already allocated
Creating mongo-to-iris-migration_mongo-seed_1 ... done

ERROR: for iris  Cannot start service iris: driver failed programming external connectivity on endpoint mongo-to-iris-migration_iris_1 (e756e1483b8f74c68049809b3edbf0c8bd1aea493668ef5c5ca8d5051300bef7): Bind for 0.0.0.0:52773 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker-compose -f "docker-compose.yml" up -d --build" terminated with exit code: 1.

**Comment by danoleg** [comment]
I think you should restart your docker to make the port free
