### ISSUE TITLE
demo docker failed to build

### ISSUE THREAD

**Issue by rcemper** [danoleg/mongo-to-iris-migration#40]
#0 10.87 W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
#0 10.87 W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
#0 10.87 E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Pac
kages  404  Not Found
#0 10.87 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
#0 10.87 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  No
t Found
#0 10.87 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends netcat &&
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*" did not complete successfully: exit code: 100

**Comment by danoleg** [comment]
Resolved
