### ISSUE TITLE
standard Docker fails to build

### ISSUE THREAD

**Issue by rcemper** [danoleg/mongo-to-iris-migration#41]
#8 9.723 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  No
t Found
#8 9.723 E: Some index files failed to download. They have been ignored, or old ones used instead.
#8 ERROR: process "/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends netcat &&     rm -r
f /var/lib/apt/lists/* /tmp/* /var/tmp/*" did not complete successfully: exit code: 100
------

**Comment by danoleg** [comment]
fixed
